### ISSUE TITLE
Runtime Issue on first run

### ISSUE THREAD

**Issue by dimarra** [deductiv/fuzzylookup#1]
Installed the version from splunkbase on Splunk Enterprise 8.1.2 running on Windows.  Is this command supported on this platform?  Thanks

Added the following call to use the command
`|fuzzylookup addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumbe`

Observations:
- `| fuzzylookup` is not being recognized a valid command and no syntax highlighting.
- 
![image](https://user-images.githubusercontent.com/1814142/112933389-7c6d5400-916b-11eb-9761-b9aac6343584.png)

splunkd.log immediately provided these messages.

>03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':  Traceback (most recent call last):
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':    File "<string>", line 1, in <module>
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':    File "F:\Splunk\Python-3.7\lib\multiprocessing\spawn.py", line 105, in spawn_main
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':      exitcode = _main(fd)
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':    File "F:\Splunk\Python-3.7\lib\multiprocessing\spawn.py", line 114, in _main
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':      prepare(preparation_data)
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':    File "F:\Splunk\Python-3.7\lib\multiprocessing\spawn.py", line 225, in prepare
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':      _fixup_main_from_path(data['init_main_from_path'])
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':    File "F:\Splunk\Python-3.7\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':      run_name="__mp_main__")
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':    File "F:\Splunk\Python-3.7\lib\runpy.py", line 263, in run_path
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':      pkg_name=pkg_name, script_name=fname)
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':    File "F:\Splunk\Python-3.7\lib\runpy.py", line 96, in _run_module_code
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':      mod_name, mod_spec, pkg_name, script_name)
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':    File "F:\Splunk\Python-3.7\lib\runpy.py", line 85, in _run_code
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':      exec(code, run_globals)
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':    File "F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py", line 68, in <module>
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':      class fuzzylookup(StreamingCommand):
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':    File "F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py", line 131, in fuzzylookup
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':      manager = Manager()
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':    File "F:\Splunk\Python-3.7\lib\multiprocessing\context.py", line 56, in Manager
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':      m.start()
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':    File "F:\Splunk\Python-3.7\lib\multiprocessing\managers.py", line 563, in start
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':      self._process.start()
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':    File "F:\Splunk\Python-3.7\lib\multiprocessing\process.py", line 112, in start
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':      self._popen = self._Popen(self)
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':    File "F:\Splunk\Python-3.7\lib\multiprocessing\context.py", line 322, in _Popen
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':      return Popen(process_obj)
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':    File "F:\Splunk\Python-3.7\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':      prep_data = spawn.get_preparation_data(process_obj._name)
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':    File "F:\Splunk\Python-3.7\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':      _check_not_importing_main()
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':    File "F:\Splunk\Python-3.7\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':      is not going to be frozen to produce an executable.''')
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':  RuntimeError: 
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':          An attempt has been made to start a new process before the
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':          current process has finished its bootstrapping phase.
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':          This probably means that you are not using fork to start your
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':          child processes and you have forgotten to use the proper idiom
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':          in the main module:
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':              if __name__ == '__main__':
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':                  freeze_support()
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':                  ...
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':          The "freeze_support()" line can be omitted if the program
03-30-2021 15:01:58.196 +1100 ERROR ScriptRunner - stderr from 'F:\Splunk\bin\Python3.exe F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py __GETINFO__ addmetrics=True prefix=mel FirstName LastName MEL-patronLookup OUTPUTNEW FirstName LastName MobileNumber':          is not going to be frozen to produce an executable.

REmoving the noise
>Traceback (most recent call last):
   File "<string>", line 1, in <module>
   File "F:\Splunk\Python-3.7\lib\multiprocessing\spawn.py", line 105, in spawn_main
     exitcode = _main(fd)
   File "F:\Splunk\Python-3.7\lib\multiprocessing\spawn.py", line 114, in _main
     prepare(preparation_data)
   File "F:\Splunk\Python-3.7\lib\multiprocessing\spawn.py", line 225, in prepare
     _fixup_main_from_path(data['init_main_from_path'])
   File "F:\Splunk\Python-3.7\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
     run_name="__mp_main__")
   File "F:\Splunk\Python-3.7\lib\runpy.py", line 263, in run_path
     pkg_name=pkg_name, script_name=fname)
   File "F:\Splunk\Python-3.7\lib\runpy.py", line 96, in _run_module_code
     mod_name, mod_spec, pkg_name, script_name)
   File "F:\Splunk\Python-3.7\lib\runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py", line 68, in <module>
     class fuzzylookup(StreamingCommand):
   File "F:\Splunk\etc\apps\fuzzylookup\bin\fuzzylookup_search.py", line 131, in fuzzylookup
     manager = Manager()
   File "F:\Splunk\Python-3.7\lib\multiprocessing\context.py", line 56, in Manager
     m.start()
   File "F:\Splunk\Python-3.7\lib\multiprocessing\managers.py", line 563, in start
     self._process.start()
   File "F:\Splunk\Python-3.7\lib\multiprocessing\process.py", line 112, in start
     self._popen = self._Popen(self)
   File "F:\Splunk\Python-3.7\lib\multiprocessing\context.py", line 322, in _Popen
     return Popen(process_obj)
   File "F:\Splunk\Python-3.7\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
     prep_data = spawn.get_preparation_data(process_obj._name)
   File "F:\Splunk\Python-3.7\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
     _check_not_importing_main()
   File "F:\Splunk\Python-3.7\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
     is not going to be frozen to produce an executable.''')
 RuntimeError: 
         An attempt has been made to start a new process before the
         current process has finished its bootstrapping phase.
         This probably means that you are not using fork to start your
         child processes and you have forgotten to use the proper idiom
         in the main module:
             if __name__ == '__main__':
                 freeze_support()
                 ...
         The "freeze_support()" line can be omitted if the program
         is not going to be frozen to produce an executable.

**Comment by jrzmurray** [comment]
Python multiprocessing requires a few extra bits on Windows. The command not being recognized is because we need a searchbnf.conf. I'll look into these shortly.

**Comment by dimarra** [comment]
Thanks for the update.  Any info when this will be resolved? Looking forward to give this a spin in our environment / use case. Thanks

**Comment by dimarra** [comment]
@jrzmurray do you have any updates to this?  thanks

**Comment by jrzmurray** [comment]
@dimarra This has been resolved with the latest commit. The updated app will appear on Splunkbase within a day or so, or you can clone this repo. Please let me know how it works out.
